package copilot

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/mariotoffia/goagentmeta/internal/domain/pipeline"
)

const provenanceHeader = "<!-- generated by goagentmeta; source: %s; do not edit -->\n"

// injectProvenanceHeaders adds a generated-file header comment to all
// instruction-layer markdown files. For files with YAML frontmatter (starting
// with "---"), the provenance comment is inserted after the closing "---"
// delimiter to avoid breaking frontmatter parsing. Extension-layer files (JSON)
// are not modified since JSON does not support comments.
func injectProvenanceHeaders(files []pipeline.EmittedFile) []pipeline.EmittedFile {
	result := make([]pipeline.EmittedFile, len(files))

	for i, f := range files {
		if f.Layer == pipeline.LayerInstruction && isMarkdown(f.Path) {
			sources := strings.Join(f.SourceObjects, ", ")
			header := fmt.Sprintf(provenanceHeader, sources)
			content := string(f.Content)

			if hasFrontmatter(content) {
				// Insert after the closing "---" to preserve frontmatter parsing.
				f.Content = []byte(insertAfterFrontmatter(content, header))
			} else {
				f.Content = append([]byte(header), f.Content...)
			}
		}
		result[i] = f
	}

	return result
}

// hasFrontmatter checks if content starts with YAML frontmatter delimiters.
func hasFrontmatter(content string) bool {
	return strings.HasPrefix(content, "---\n") || strings.HasPrefix(content, "---\r\n")
}

// insertAfterFrontmatter inserts text after the closing "---" frontmatter delimiter.
func insertAfterFrontmatter(content, insert string) string {
	// Find the closing "---" (skip the opening one).
	rest := content[3:] // skip "---"
	idx := strings.Index(rest, "\n---\n")
	if idx < 0 {
		// Try with \r\n.
		idx = strings.Index(rest, "\r\n---\r\n")
		if idx < 0 {
			// No closing delimiter found; prepend.
			return insert + content
		}
		closeEnd := 3 + idx + len("\r\n---\r\n")
		return content[:closeEnd] + insert + content[closeEnd:]
	}
	closeEnd := 3 + idx + len("\n---\n")
	return content[:closeEnd] + insert + content[closeEnd:]
}

// renderProvenance generates a provenance.json file listing all source objects
// and output files for the build unit.
func renderProvenance(unitKey string, files []pipeline.EmittedFile) pipeline.EmittedFile {
	entries := make([]provenanceEntry, 0, len(files))

	sourceToOutputs := make(map[string][]string)
	for _, f := range files {
		for _, src := range f.SourceObjects {
			sourceToOutputs[src] = append(sourceToOutputs[src], f.Path)
		}
	}

	sourceKeys := make([]string, 0, len(sourceToOutputs))
	for k := range sourceToOutputs {
		sourceKeys = append(sourceKeys, k)
	}
	sort.Strings(sourceKeys)

	for _, src := range sourceKeys {
		outputs := sourceToOutputs[src]
		sort.Strings(outputs)
		entries = append(entries, provenanceEntry{
			SourceObject: src,
			OutputFiles:  outputs,
		})
	}

	prov := provenanceJSON{
		BuildUnit: unitKey,
		Target:    "copilot",
		Entries:   entries,
	}

	data, err := json.MarshalIndent(prov, "", "  ")
	if err != nil {
		data = []byte("{}")
	}

	data = append(data, '\n')

	var allSources []string
	for _, e := range entries {
		allSources = append(allSources, e.SourceObject)
	}

	return pipeline.EmittedFile{
		Path:          "provenance.json",
		Content:       data,
		Layer:         pipeline.LayerExtension,
		SourceObjects: allSources,
	}
}

// provenanceJSON is the structure of provenance.json.
type provenanceJSON struct {
	BuildUnit string            `json:"buildUnit"`
	Target    string            `json:"target"`
	Entries   []provenanceEntry `json:"entries"`
}

// provenanceEntry maps a source object to the output files it contributed to.
type provenanceEntry struct {
	SourceObject string   `json:"sourceObject"`
	OutputFiles  []string `json:"outputFiles"`
}

// isMarkdown checks if a file path ends with .md.
func isMarkdown(path string) bool {
	return strings.HasSuffix(path, ".md")
}
