// Package marketplace defines the port interface for generating marketplace
// catalogs from domain marketplace models. Generators transform the
// target-agnostic marketplace domain types into target-native catalog formats
// (e.g., Claude Code's marketplace.json, Cursor marketplace refs, etc.).
//
// This package is a hexagonal port: it defines contracts that adapters implement.
// New marketplace formats are added by implementing the Generator interface and
// registering with a GeneratorRegistry — no changes to the core pipeline are needed.
package marketplace

import (
	"context"
	"fmt"
	"sync"

	domain "github.com/mariotoffia/goagentmeta/internal/domain/marketplace"
	"github.com/mariotoffia/goagentmeta/internal/port/packager"
)

// TargetFormat identifies a marketplace catalog format. It is a semi-open
// string enum: well-known values are provided as constants, but custom values
// are permitted to support future marketplace formats.
type TargetFormat string

const (
	// FormatClaude produces Claude Code-compatible marketplace.json.
	FormatClaude TargetFormat = "claude"
	// FormatCursor produces Cursor-compatible marketplace references.
	FormatCursor TargetFormat = "cursor"
	// FormatCopilot produces Copilot-compatible marketplace references.
	FormatCopilot TargetFormat = "copilot"
)

// Generator produces a marketplace catalog in a target-native format.
type Generator interface {
	// Format returns the marketplace format this generator produces.
	Format() TargetFormat

	// Generate creates the marketplace catalog structure from the domain model.
	Generate(ctx context.Context, input GeneratorInput) (*GeneratorOutput, error)
}

// GeneratorInput provides everything a generator needs to produce a catalog.
type GeneratorInput struct {
	// Marketplace is the domain model to generate from.
	Marketplace domain.Marketplace

	// PluginArtifacts are the packaged plugin artifacts that may be referenced
	// by the catalog (e.g., for relative path sources).
	PluginArtifacts []packager.PackagedArtifact

	// OutputDir is the base directory where catalog files should be written.
	OutputDir string
}

// GeneratorOutput holds the results of marketplace generation.
type GeneratorOutput struct {
	// CatalogPath is the filesystem path to the generated catalog file
	// (e.g., .claude-plugin/marketplace.json).
	CatalogPath string

	// Files lists all files generated by the generator.
	Files []string

	// Metadata carries format-specific key-value data.
	Metadata map[string]string
}

// GeneratorRegistry manages generator registrations and provides lookup by format.
// Implementations must be safe for concurrent use.
type GeneratorRegistry interface {
	// Register adds a generator. Returns an error if the format is already registered.
	Register(g Generator) error

	// MustRegister is like Register but panics on error.
	MustRegister(g Generator)

	// ByFormat returns the generator for the given format, or false if none is registered.
	ByFormat(f TargetFormat) (Generator, bool)

	// All returns all registered generators in registration order.
	All() []Generator
}

// DefaultRegistry is a thread-safe in-memory GeneratorRegistry.
type DefaultRegistry struct {
	mu   sync.RWMutex
	idx  map[TargetFormat]int
	gens []Generator
}

// NewRegistry creates an empty DefaultRegistry.
func NewRegistry() *DefaultRegistry {
	return &DefaultRegistry{
		idx: make(map[TargetFormat]int),
	}
}

// Register adds a generator.
func (r *DefaultRegistry) Register(g Generator) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	f := g.Format()
	if _, exists := r.idx[f]; exists {
		return fmt.Errorf("marketplace generator already registered for format %q", f)
	}

	r.idx[f] = len(r.gens)
	r.gens = append(r.gens, g)

	return nil
}

// MustRegister panics on error.
func (r *DefaultRegistry) MustRegister(g Generator) {
	if err := r.Register(g); err != nil {
		panic(err)
	}
}

// ByFormat returns the generator for the given format.
func (r *DefaultRegistry) ByFormat(f TargetFormat) (Generator, bool) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	i, ok := r.idx[f]
	if !ok {
		return nil, false
	}

	return r.gens[i], true
}

// All returns all registered generators.
func (r *DefaultRegistry) All() []Generator {
	r.mu.RLock()
	defer r.mu.RUnlock()

	out := make([]Generator, len(r.gens))
	copy(out, r.gens)

	return out
}

// Compile-time assertion.
var _ GeneratorRegistry = (*DefaultRegistry)(nil)
