package codex

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/mariotoffia/goagentmeta/internal/domain/pipeline"
)

const provenanceHeader = "<!-- generated by goagentmeta; source: %s; do not edit -->\n"

// injectProvenanceHeaders prepends a generated-file header comment to all
// instruction-layer markdown files. Extension-layer files (JSON) are not
// modified since JSON does not support comments.
func injectProvenanceHeaders(files []pipeline.EmittedFile) []pipeline.EmittedFile {
	result := make([]pipeline.EmittedFile, len(files))

	for i, f := range files {
		if f.Layer == pipeline.LayerInstruction && isMarkdown(f.Path) {
			sources := strings.Join(f.SourceObjects, ", ")
			header := fmt.Sprintf(provenanceHeader, sources)
			f.Content = append([]byte(header), f.Content...)
		}
		result[i] = f
	}

	return result
}

// renderProvenance generates a provenance.json file listing all source objects
// and output files for the build unit.
func renderProvenance(unitKey string, files []pipeline.EmittedFile) pipeline.EmittedFile {
	entries := make([]provenanceEntry, 0, len(files))

	sourceToOutputs := make(map[string][]string)
	for _, f := range files {
		for _, src := range f.SourceObjects {
			sourceToOutputs[src] = append(sourceToOutputs[src], f.Path)
		}
	}

	sourceKeys := make([]string, 0, len(sourceToOutputs))
	for k := range sourceToOutputs {
		sourceKeys = append(sourceKeys, k)
	}
	sort.Strings(sourceKeys)

	for _, src := range sourceKeys {
		outputs := sourceToOutputs[src]
		sort.Strings(outputs)
		entries = append(entries, provenanceEntry{
			SourceObject: src,
			OutputFiles:  outputs,
		})
	}

	prov := provenanceJSON{
		BuildUnit: unitKey,
		Target:    "codex",
		Entries:   entries,
	}

	data, err := json.MarshalIndent(prov, "", "  ")
	if err != nil {
		data = []byte("{}")
	}

	data = append(data, '\n')

	var allSources []string
	for _, e := range entries {
		allSources = append(allSources, e.SourceObject)
	}

	return pipeline.EmittedFile{
		Path:          "provenance.json",
		Content:       data,
		Layer:         pipeline.LayerExtension,
		SourceObjects: allSources,
	}
}

// provenanceJSON is the structure of provenance.json.
type provenanceJSON struct {
	BuildUnit string            `json:"buildUnit"`
	Target    string            `json:"target"`
	Entries   []provenanceEntry `json:"entries"`
}

// provenanceEntry maps a source object to the output files it contributed to.
type provenanceEntry struct {
	SourceObject string   `json:"sourceObject"`
	OutputFiles  []string `json:"outputFiles"`
}

// isMarkdown checks if a file path ends with .md.
func isMarkdown(path string) bool {
	return strings.HasSuffix(path, ".md")
}
